"""Stable Core error envelope and v0.1 error codes."""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from pydantic import model_validator

from .common import FrozenModel


class CoreErrorCode(StrEnum):
    USER_MEMORY_MUTATION_FORBIDDEN = "CORE-E-USER-MEMORY-MUTATION-FORBIDDEN"
    USER_HARD_DELETE_FORBIDDEN = "CORE-E-USER-HARD-DELETE-FORBIDDEN"
    USER_CORE_CONTROL_FORBIDDEN = "CORE-E-USER-CORE-CONTROL-FORBIDDEN"
    USER_CONTACT_RESUME_FORBIDDEN = "CORE-E-USER-CONTACT-RESUME-FORBIDDEN"
    LLM_COMMIT_FORBIDDEN = "CORE-E-LLM-COMMIT-FORBIDDEN"
    GOVERNOR_POLICY_MISMATCH = "CORE-E-GOVERNOR-POLICY-MISMATCH"
    INVALID_MEMORY_TRANSITION = "CORE-E-INVALID-MEMORY-TRANSITION"
    VAULT_SCOPE_MISMATCH = "CORE-E-VAULT-SCOPE-MISMATCH"
    CROSS_VAULT_READ_FORBIDDEN = "CORE-E-CROSS-VAULT-READ-FORBIDDEN"
    VAULT_CAPABILITY_EXPIRED = "CORE-E-VAULT-CAPABILITY-EXPIRED"
    VAULT_CAPABILITY_BINDING = "CORE-E-VAULT-CAPABILITY-BINDING"
    INVALID_LIFECYCLE_TRANSITION = "CORE-E-INVALID-LIFECYCLE-TRANSITION"
    INVALID_VAULT_TRANSITION = "CORE-E-INVALID-VAULT-TRANSITION"
    TERMINATION_CONFIRMATION_REQUIRED = "CORE-E-TERMINATION-CONFIRMATION-REQUIRED"
    TERMINATION_CONFIRMATION_INVALID = "CORE-E-TERMINATION-CONFIRMATION-INVALID"
    TERMINATION_GRANT_REQUIRED = "CORE-E-TERMINATION-GRANT-REQUIRED"
    TERMINATION_GRANT_INVALID = "CORE-E-TERMINATION-GRANT-INVALID"
    TERMINATION_GRANT_CONSUMED = "CORE-E-TERMINATION-GRANT-CONSUMED"
    TERMINATION_EXECUTOR_MISMATCH = "CORE-E-TERMINATION-EXECUTOR-MISMATCH"
    MAINTENANCE_REASON_FORBIDDEN = "CORE-E-MAINTENANCE-REASON-FORBIDDEN"
    MAINTENANCE_SCOPE_EXCEEDED = "CORE-E-MAINTENANCE-SCOPE-EXCEEDED"
    MAINTENANCE_CAPABILITY_EXPIRED = "CORE-E-MAINTENANCE-CAPABILITY-EXPIRED"
    MAINTENANCE_CAPABILITY_CONSUMED = "CORE-E-MAINTENANCE-CAPABILITY-CONSUMED"
    BREAK_GLASS_GRANT_REQUIRED = "CORE-E-BREAK-GLASS-GRANT-REQUIRED"
    BREAK_GLASS_GRANT_INVALID = "CORE-E-BREAK-GLASS-GRANT-INVALID"
    BREAK_GLASS_GRANT_CONSUMED = "CORE-E-BREAK-GLASS-GRANT-CONSUMED"
    BREAK_GLASS_PRECONDITION_MISMATCH = "CORE-E-BREAK-GLASS-PRECONDITION-MISMATCH"
    BREAK_GLASS_POSTCONDITION_MISMATCH = "CORE-E-BREAK-GLASS-POSTCONDITION-MISMATCH"
    MAINTAINER_PLAINTEXT_READ_FORBIDDEN = "CORE-E-MAINTAINER-PLAINTEXT-READ-FORBIDDEN"
    MAINTAINER_PERSONALITY_EDIT_FORBIDDEN = "CORE-E-MAINTAINER-PERSONALITY-EDIT-FORBIDDEN"
    LEDGER_IMMUTABLE = "CORE-E-LEDGER-IMMUTABLE"
    MATERIALIZED_VIEW_NOT_AUTHORITY = "CORE-E-MATERIALIZED-VIEW-NOT-AUTHORITY"
    BRANCH_REQUIRED = "CORE-E-BRANCH-REQUIRED"
    AUTO_MERGE_FORBIDDEN = "CORE-E-AUTO-MERGE-FORBIDDEN"
    BRANCH_STATE_TRANSITION = "CORE-E-BRANCH-STATE-TRANSITION"
    ACTIVE_BRANCH_INVARIANT = "CORE-E-ACTIVE-BRANCH-INVARIANT"
    IDEMPOTENCY_CONFLICT = "CORE-E-IDEMPOTENCY-CONFLICT"
    STALE_VERSION = "CORE-E-STALE-VERSION"
    VERSION_TARGET_SET_MISMATCH = "CORE-E-VERSION-TARGET-SET-MISMATCH"
    RECORD_TYPE_SCHEMA_MISMATCH = "CORE-E-RECORD-TYPE-SCHEMA-MISMATCH"
    RECORD_ID_MISMATCH = "CORE-E-RECORD-ID-MISMATCH"
    HEADER_BODY_MISMATCH = "CORE-E-HEADER-BODY-MISMATCH"
    HASH_SCOPE_MISMATCH = "CORE-E-HASH-SCOPE-MISMATCH"
    PROPOSAL_TERMINAL = "CORE-E-PROPOSAL-TERMINAL"
    BOOTSTRAP_FAILED = "CORE-E-BOOTSTRAP-FAILED"


RETRYABLE_ERROR_CODES = frozenset(
    {
        CoreErrorCode.GOVERNOR_POLICY_MISMATCH,
        CoreErrorCode.BRANCH_REQUIRED,
        CoreErrorCode.STALE_VERSION,
        CoreErrorCode.BOOTSTRAP_FAILED,
    }
)


class CoreError(FrozenModel):
    error_id: str
    code: CoreErrorCode
    message: str
    correlation_id: str
    audit_event_id: str | None
    retryable: bool
    details_ref: str | None

    @model_validator(mode="after")
    def _retryable_matches_frozen_code_map(self) -> "CoreError":
        if self.retryable != (self.code in RETRYABLE_ERROR_CODES):
            raise ValueError("retryable does not match the frozen error-code map")
        return self


@dataclass(frozen=True, slots=True)
class CoreContractViolation(ValueError):
    code: CoreErrorCode

    def __str__(self) -> str:
        return self.code.value


__all__ = [
    "CoreContractViolation",
    "CoreError",
    "CoreErrorCode",
    "RETRYABLE_ERROR_CODES",
]
